### ISSUE TITLE
No need to wait for Wire.available().

### ISSUE THREAD

**Issue by Koepel** [adafruit/Adafruit-Si4713-Library#1]
This code is used twice: "Wire.available() < 1".
But there is no need to wait for data. After the Wire.requestFrom() the I2C transmission has completely ended.
To check if valid data was received, the return value of Wire.requestFrom() or Wire.available() can be checked if that is the same number of bytes as requested.

**Comment by hoffmannjan** [comment]
Hi, thanks for your suggestion, It was added in #4 .
